comment: false

coverage:
  status:
    project:
      minimum-70:
        target: 70%
        threshold: 0%
      no-regress:
        target: auto
        threshold: 0%
        base: auto

if_ci_failed: error

fixes:
  - "/workspace/::"
