comment: false

coverage:
  status:
    project: false
    patch: false
    changes:
      default:
        target: 70%
        threshold: 10%
        base: auto
        if_ci_failed: error
        if_not_found: error

fixes:
  - "/workspace/::"
