override-dependencies = [
    "flash-attn; sys_platform == 'never'",
    "nvidia-cublas-cu12; sys_platform == 'never'",
    "nvidia-cuda-cupti-cu12; sys_platform == 'never'",
    "nvidia-cuda-nvrtc-cu12; sys_platform == 'never'",
    "nvidia-cuda-runtime-cu12; sys_platform == 'never'",
    "nvidia-cudnn-cu12; sys_platform == 'never'",
    "nvidia-cufft-cu12; sys_platform == 'never'",
    "nvidia-cufile-cu12; sys_platform == 'never'",
    "nvidia-curand-cu12; sys_platform == 'never'",
    "nvidia-cusolver-cu12; sys_platform == 'never'",
    "nvidia-cusparse-cu12; sys_platform == 'never'",
    "nvidia-cusparselt-cu12; sys_platform == 'never'",
    "nvidia-nccl-cu12; sys_platform == 'never'",
    "torch; sys_platform == 'never'",
    "torchvision; sys_platform == 'never'",
    "triton; sys_platform == 'never'",
]
