# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# 4 nodes(8xh200)
# torchrun --nproc-per-node=8 --nnodes=4 --rdzv_backend=c10d --master_addr=$MASTER_ADDR --master_port=$MASTER_PORT examples/llm_finetune/finetune.py --config examples/llm_finetune/llama3_3/llama_3_3_70b_instruct_squad.yaml

step_scheduler:
  global_batch_size: 256
  local_batch_size: 32
  ckpt_every_steps: 50
  val_every_steps: 1000
  max_steps: 100

dist_env:
  backend: nccl
  timeout_minutes: 1

rng:
  _target_: nemo_automodel.components.training.rng.StatefulRNG
  seed: 1111
  ranked: true

model:
  _target_: nemo_automodel.NeMoAutoModelForCausalLM.from_pretrained
  pretrained_model_name_or_path: meta-llama/Llama-3.3-70B-Instruct
  torch_dtype: bf16
  trust_remote_code: true

checkpoint:
  enabled: true
  checkpoint_dir: checkpoints/
  model_save_format: torch_save # torch_save or safetensors
  save_consolidated: false

distributed:
  _target_: nemo_automodel.components.distributed.fsdp2.FSDP2Manager
  dp_size: none
  tp_size: 1
  cp_size: 1
  pp_size: 8
  sequence_parallel: false

loss_fn:
  _target_: nemo_automodel.components.loss.masked_ce.MaskedCrossEntropy

# SQuAD instruction tuning dataset (5% train split for quick runs)
dataset:
  _target_: nemo_automodel.components.datasets.llm.squad.make_squad_dataset
  dataset_name: rajpurkar/squad
  split: train

packed_sequence:
  packed_sequence_size: 1024
  split_across_pack: false

# StatefulDataLoader with default collate
dataloader:
  _target_: torchdata.stateful_dataloader.StatefulDataLoader
  collate_fn: nemo_automodel.components.datasets.utils.default_collater
  shuffle: true

validation_dataset:
  _target_: nemo_automodel.components.datasets.llm.squad.make_squad_dataset
  dataset_name: rajpurkar/squad
  split: validation

validation_dataloader:
  _target_: torchdata.stateful_dataloader.StatefulDataLoader
  collate_fn: nemo_automodel.components.datasets.utils.default_collater

optimizer:
  _target_: torch.optim.Adam
  betas: [0.9, 0.999]
  eps: 1e-8
  lr: 1.0e-5
  weight_decay: 0

# AutoPipeline configuration for PP scheduling
autopipeline:
  _target_: nemo_automodel.components.distributed.pipelining.autopipeline.AutoPipeline
  pp_schedule: interleaved1f1b
  pp_microbatch_size: 4
  scale_grads_in_schedule: false

lr_scheduler:
  lr_decay_style: cosine
  min_lr: 1.0e-6 