# Copyright (c) 2026, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""ViSpec draft-training recipe for vision-language targets (stage 2).

ViSpec (arXiv:2509.15235) trains in two stages:

1. **Stage 1 -- text only.** Plain EAGLE-1/2 training on a text corpus; use
   ``TrainEagle2Recipe``. The resulting draft has no vision modules yet.
2. **Stage 2 -- vision aware.** This recipe. It loads the stage-1 draft through
   ``recipe_args.draft_init_from``, adds the image adaptor and the global-image
   projection, and trains on image+text conversations whose assistant turns were
   regenerated by the target VLM (see
   ``nemo_automodel/components/speculative/regenerate_vlm.py``).

The training loop, checkpointing, and resume behavior are inherited from
``TrainEagle1Recipe``; only the model/data construction and the per-batch
supervision differ.
"""

from __future__ import annotations

import copy
import logging

import torch
from safetensors.torch import load_file
from torch.nn.parallel import DistributedDataParallel
from transformers import AutoConfig, AutoProcessor

from nemo_automodel._transformers import NeMoAutoModelForImageTextToText
from nemo_automodel._transformers.auto_tokenizer import NeMoAutoTokenizer
from nemo_automodel.components.config._arg_parser import parse_args_and_load_config
from nemo_automodel.components.datasets.llm.eagle3 import build_eagle3_dataloader
from nemo_automodel.components.datasets.vlm.dspark_collate import build_dspark_vlm_dataloader
from nemo_automodel.components.distributed.init_utils import initialize_distributed
from nemo_automodel.components.loggers.log_utils import setup_logging
from nemo_automodel.components.speculative.eagle.core_v12 import EagleTrainerModule
from nemo_automodel.components.speculative.eagle.registry import (
    resolve_vispec_draft_spec,
    resolve_vispec_stage1_draft_spec,
)
from nemo_automodel.components.speculative.eagle.target_v12 import HFEagleTargetModel
from nemo_automodel.components.speculative.eagle.vispec_core import VispecTrainerModule
from nemo_automodel.components.speculative.eagle.vispec_target import HFVispecTargetModel
from nemo_automodel.components.utils.model_utils import print_trainable_parameters
from nemo_automodel.recipes.llm.train_eagle1 import TrainEagle1Recipe

logger = logging.getLogger(__name__)


def _resolve_image_token_id(target_config, processor) -> int:
    """Resolve the target's image-placeholder token id.

    Args:
        target_config: The target VLM's HuggingFace config.
        processor: The target's ``AutoProcessor``.

    Returns:
        The token id that marks an image position in ``input_ids``.
    """
    image_token_id = getattr(target_config, "image_token_id", None)
    if image_token_id is not None:
        return int(image_token_id)
    image_token = getattr(processor, "image_token", None)
    if image_token is None:
        raise ValueError(
            "Could not resolve the target's image token: neither config.image_token_id nor "
            "processor.image_token is set. ViSpec needs it to locate the image positions to compress."
        )
    return int(processor.tokenizer.convert_tokens_to_ids(image_token))


def _seed_draft_initialization(recipe_cfg) -> int:
    """Seed ViSpec draft initialization and training-time stochasticity.

    ``shuffle_seed`` predates the explicit ``seed`` knob and remains the
    backwards-compatible default. Seeding must happen before the draft is
    constructed because the frozen target is loaded from checkpoints while the
    draft starts from random weights.
    """
    seed = int(recipe_cfg.get("seed", recipe_cfg.get("shuffle_seed", 42)))
    torch.manual_seed(seed)
    return seed


class TrainVispecRecipe(TrainEagle1Recipe):
    """Recipe for ViSpec stage-2 (vision-aware) draft training."""

    def setup(self):
        """Build the frozen VLM target, the ViSpec draft, data, optimizer, and trainer module."""
        self.dist_env = initialize_distributed(
            backend=self.cfg.get("dist_env", {}).get("backend", "nccl"),
            timeout_minutes=self.cfg.get("dist_env", {}).get("timeout_minutes", 30),
        )
        setup_logging()

        recipe_cfg = self.cfg.recipe_args
        self.device = self.dist_env.device or torch.device("cpu")
        # The draft compresses per-sample image spans, so its sequence length is
        # sample-dependent and cannot be batched. Gradient accumulation, not a
        # larger micro-batch, is how this recipe scales its effective batch size.
        micro_batch_size = int(recipe_cfg.get("micro_batch_size", 1))
        if micro_batch_size != 1:
            raise ValueError(
                f"ViSpec training requires recipe_args.micro_batch_size=1 (got {micro_batch_size}); "
                "raise grad_accumulation_steps instead."
            )
        # EAGLE-1/2 sharded-target knobs are not wired up for the VLM target here.
        self.dp_mesh = None
        self.moe_mesh = None
        self.device_mesh = None
        self.dist_setup = None

        target_path = recipe_cfg.target_model_name_or_path
        trust_remote_code = bool(recipe_cfg.get("trust_remote_code", False))
        target_config = AutoConfig.from_pretrained(target_path, trust_remote_code=trust_remote_code)
        architectures = getattr(target_config, "architectures", []) or []
        draft_spec = resolve_vispec_draft_spec(architectures)

        self.tokenizer = NeMoAutoTokenizer.from_pretrained(target_path, trust_remote_code=trust_remote_code)
        self.processor = AutoProcessor.from_pretrained(target_path, trust_remote_code=trust_remote_code)
        self.compute_dtype = torch.bfloat16 if self.device.type == "cuda" else torch.float32

        self.target_model = NeMoAutoModelForImageTextToText.from_pretrained(
            target_path,
            trust_remote_code=trust_remote_code,
            torch_dtype=self.compute_dtype,
            force_hf=bool(recipe_cfg.get("target_force_hf", True)),
        )
        self.target_model.to(self.device)
        self.target_model.requires_grad_(False)
        self.target_wrapper = HFVispecTargetModel(
            self.target_model,
            image_token_id=_resolve_image_token_id(target_config, self.processor),
        )

        self.train_dataloader = build_dspark_vlm_dataloader(
            dataset_cfg=self.cfg.dataset,
            processor=self.processor,
            batch_size=micro_batch_size,
            max_length=recipe_cfg.seq_length,
            shuffle=True,
            num_workers=recipe_cfg.get("num_workers", 0),
            distributed=self.dist_env.world_size > 1,
        )
        self.val_dataloader = None
        if self.cfg.get("val_dataset", None) is not None:
            self.val_dataloader = build_dspark_vlm_dataloader(
                dataset_cfg=self.cfg.val_dataset,
                processor=self.processor,
                batch_size=micro_batch_size,
                max_length=recipe_cfg.seq_length,
                shuffle=False,
                num_workers=recipe_cfg.get("num_workers", 0),
                distributed=self.dist_env.world_size > 1,
            )

        # The draft is a text-only transformer over the target's language tower,
        # so it reads the text sub-config (hidden size, heads, RoPE, vocab).
        draft_config = copy.deepcopy(target_config.get_text_config())
        draft_config.architectures = ["VispecDraftModel"]
        draft_config.draft_num_hidden_layers = int(recipe_cfg.get("draft_num_hidden_layers", 1))
        draft_config.vispec_num_query_tokens = int(recipe_cfg.get("num_query_tokens", 2))
        _seed_draft_initialization(recipe_cfg)
        self.draft_model = draft_spec.draft_cls(draft_config).to(device=self.device, dtype=self.compute_dtype)
        self.draft_model.copy_embeddings_from_target(self.target_wrapper.get_input_embeddings())
        if recipe_cfg.get("freeze_embeddings", True):
            self.draft_model.freeze_embeddings()
        self._load_stage1_draft(recipe_cfg.get("draft_init_from", None))
        print_trainable_parameters(self.draft_model, name="Draft")

        trainer_module = VispecTrainerModule(
            self.draft_model,
            target_lm_head=self.target_wrapper.get_lm_head(),
            prob_loss_weight=float(recipe_cfg.get("prob_loss_weight", 10.0)),
            rank_loss_weight=float(recipe_cfg.get("rank_loss_weight", 0.1)),
            rank_loss_topk=int(recipe_cfg.get("rank_loss_topk", 10)),
            mtp_steps=int(recipe_cfg.get("mtp_steps", 1)),
        ).to(self.device)
        if self.dist_env.world_size > 1:
            trainer_module = DistributedDataParallel(
                trainer_module,
                device_ids=[self.device.index] if self.device.type == "cuda" else None,
                output_device=self.device.index if self.device.type == "cuda" else None,
                broadcast_buffers=False,
                find_unused_parameters=False,
            )
        self.trainer_module = trainer_module

        self._finalize_setup(recipe_cfg=recipe_cfg, target_path=target_path, wandb_name_prefix="vispec_")

    def _load_stage1_draft(self, draft_init_from: str | None) -> None:
        """Initialize the shared draft weights from a stage-1 EAGLE-1/2 checkpoint.

        The ViSpec-only modules (``img_adaptor``, ``img_fc``) are absent from a
        stage-1 checkpoint and keep their fresh initialization, which starts as
        an identity pass-through, so stage 2 begins numerically equal to stage 1.

        Args:
            draft_init_from: Path to a stage-1 ``model.safetensors`` file, or
                ``None`` to train the draft from scratch.
        """
        if not draft_init_from:
            return
        state_dict = load_file(draft_init_from)
        missing, unexpected = self.draft_model.load_state_dict(state_dict, strict=False)
        vispec_only = {name for name in missing if name.startswith(("img_adaptor.", "img_fc."))}
        unresolved = [name for name in missing if name not in vispec_only]
        if unresolved:
            raise ValueError(
                f"Stage-1 checkpoint {draft_init_from} is missing draft weights {sorted(unresolved)}; "
                "it does not match this draft configuration."
            )
        if unexpected:
            logger.warning("Ignoring %d unexpected key(s) in %s", len(unexpected), draft_init_from)
        logger.info("Initialized the ViSpec draft from stage-1 checkpoint %s", draft_init_from)

    def _compute_metrics(self, batch: dict[str, torch.Tensor]):
        """Run the frozen VLM target and the ViSpec draft over one micro-batch.

        Args:
            batch: Dataloader batch already on ``self.device``, carrying
                ``input_ids`` / ``attention_mask`` / ``loss_mask`` of shape
                [1, sequence] plus the processor's vision tensors.

        Returns:
            VispecStepMetrics for this micro-batch.
        """
        vision_inputs = {
            key: value for key, value in batch.items() if key not in ("input_ids", "attention_mask", "loss_mask")
        }
        target_batch = self.target_wrapper.generate_batch(
            input_ids=batch["input_ids"],
            attention_mask=batch["attention_mask"],
            loss_mask=batch["loss_mask"],
            **vision_inputs,
        )
        return self.trainer_module(
            inputs_embeds=target_batch.inputs_embeds,
            attention_mask=target_batch.attention_mask,
            loss_mask=target_batch.loss_mask,
            input_hidden_states=target_batch.input_hidden_states,
            target_logits=target_batch.target_logits,
            image_mask=target_batch.image_mask,
        )

    def _loss_components(self, metrics) -> dict[str, float]:
        """Return ViSpec's two loss terms for logging.

        Args:
            metrics: The :class:`VispecStepMetrics` returned by :meth:`_compute_metrics`.

        Returns:
            Mapping of log-suffix to scalar value, logged as ``train/<key>``.
        """
        return {
            "prob_loss": metrics.prob_loss.detach().item(),
            "rank_loss": metrics.rank_loss.detach().item(),
        }


class TrainVispecStage1Recipe(TrainEagle1Recipe):
    """Train ViSpec's text-only EAGLE draft with a frozen VLM teacher.

    ViSpec's first stage does not consume images or construct ViSpec's image
    adaptor. It does, however, use the intended VLM's language tower as the
    teacher, so the draft learns the target's text decoding distribution before
    stage 2 adds vision-aware training.
    """

    def setup(self):
        """Build the frozen VLM teacher and text-only EAGLE draft for stage 1."""
        self.dist_env = initialize_distributed(
            backend=self.cfg.get("dist_env", {}).get("backend", "nccl"),
            timeout_minutes=self.cfg.get("dist_env", {}).get("timeout_minutes", 30),
        )
        setup_logging()

        if self.cfg.get("distributed", None) is not None:
            raise NotImplementedError(
                "TrainVispecStage1Recipe does not support target-model sharding yet. "
                "Use one target VLM replica per rank without a `distributed:` section."
            )

        recipe_cfg = self.cfg.recipe_args
        self.device = self.dist_env.device or torch.device("cpu")
        self.dp_mesh = None
        self.moe_mesh = None
        self.device_mesh = None
        self.dist_setup = None

        target_path = recipe_cfg.target_model_name_or_path
        trust_remote_code = bool(recipe_cfg.get("trust_remote_code", False))
        target_config = AutoConfig.from_pretrained(target_path, trust_remote_code=trust_remote_code)
        architectures = getattr(target_config, "architectures", []) or []
        draft_spec = resolve_vispec_stage1_draft_spec(architectures)

        self.tokenizer = NeMoAutoTokenizer.from_pretrained(target_path, trust_remote_code=trust_remote_code)
        self.compute_dtype = torch.bfloat16 if self.device.type == "cuda" else torch.float32
        self.target_model = NeMoAutoModelForImageTextToText.from_pretrained(
            target_path,
            trust_remote_code=trust_remote_code,
            torch_dtype=self.compute_dtype,
            force_hf=bool(recipe_cfg.get("target_force_hf", True)),
        )
        self.target_model.to(self.device)
        self.target_model.requires_grad_(False)
        self.target_wrapper = HFEagleTargetModel(self.target_model)

        packed_sequence_size = int(recipe_cfg.get("packed_sequence_size", 0) or 0)
        if packed_sequence_size > 0:
            raise NotImplementedError(
                "TrainVispecStage1Recipe does not support packed_sequence_size because VLM text towers "
                "may use multimodal RoPE. Set packed_sequence_size=0."
            )
        self.train_dataloader = build_eagle3_dataloader(
            data_path=recipe_cfg.train_data_path,
            tokenizer=self.tokenizer,
            seq_length=recipe_cfg.seq_length,
            batch_size=recipe_cfg.micro_batch_size,
            shuffle=True,
            num_workers=recipe_cfg.get("num_workers", 0),
            split=recipe_cfg.get("train_split", None),
            distributed=self.dist_env.world_size > 1,
            shuffle_seed=recipe_cfg.get("shuffle_seed", 42),
            mask_reasoning_content=recipe_cfg.get("mask_reasoning_content", False),
            packed_sequence_size=0,
        )
        self.val_dataloader = None
        if recipe_cfg.get("val_data_path", None):
            self.val_dataloader = build_eagle3_dataloader(
                data_path=recipe_cfg.val_data_path,
                tokenizer=self.tokenizer,
                seq_length=recipe_cfg.seq_length,
                batch_size=recipe_cfg.micro_batch_size,
                shuffle=False,
                num_workers=recipe_cfg.get("num_workers", 0),
                split=recipe_cfg.get("val_split", None),
                distributed=self.dist_env.world_size > 1,
                shuffle_seed=recipe_cfg.get("shuffle_seed", 42),
                mask_reasoning_content=recipe_cfg.get("mask_reasoning_content", False),
                packed_sequence_size=0,
            )

        draft_config = copy.deepcopy(target_config.get_text_config())
        draft_config.architectures = ["LlamaEagleDraftModel"]
        draft_config.draft_num_hidden_layers = int(recipe_cfg.get("draft_num_hidden_layers", 1))
        _seed_draft_initialization(recipe_cfg)
        self.draft_model = draft_spec.draft_cls(draft_config).to(device=self.device, dtype=self.compute_dtype)
        self.draft_model.copy_embeddings_from_target(self.target_wrapper.get_input_embeddings())
        if recipe_cfg.get("freeze_embeddings", True):
            self.draft_model.freeze_embeddings()
        print_trainable_parameters(self.draft_model, name="Draft")

        trainer_module = EagleTrainerModule(
            self.draft_model,
            target_lm_head=self.target_wrapper.get_lm_head(),
            hidden_loss_weight=float(recipe_cfg.get("hidden_loss_weight", 1.0)),
            token_loss_weight=float(recipe_cfg.get("token_loss_weight", 0.1)),
            feature_noise=float(recipe_cfg.get("feature_noise", 0.1)),
        ).to(self.device)
        if self.dist_env.world_size > 1:
            trainer_module = DistributedDataParallel(
                trainer_module,
                device_ids=[self.device.index] if self.device.type == "cuda" else None,
                output_device=self.device.index if self.device.type == "cuda" else None,
                broadcast_buffers=False,
                find_unused_parameters=False,
            )
        self.trainer_module = trainer_module

        self._finalize_setup(recipe_cfg=recipe_cfg, target_path=target_path, wandb_name_prefix="vispec_stage1_")


def main(config_path: str | None = None):
    """Entrypoint for the ViSpec stage selected by the recipe config.

    Args:
        config_path: Optional default YAML path. The command-line ``--config``
            argument overrides this value.

    Raises:
        ValueError: If ``recipe`` is not a supported ViSpec recipe name.
    """
    cfg = parse_args_and_load_config(config_path)
    recipe_name = cfg.get("recipe", "TrainVispecRecipe")
    if recipe_name == "TrainVispecStage1Recipe":
        recipe_cls = TrainVispecStage1Recipe
    elif recipe_name == "TrainVispecRecipe":
        recipe_cls = TrainVispecRecipe
    else:
        raise ValueError(
            f"Unsupported ViSpec recipe {recipe_name!r}; expected 'TrainVispecStage1Recipe' or 'TrainVispecRecipe'."
        )
    trainer = recipe_cls(cfg)
    trainer.setup()
    trainer.run_train_validation_loop()


if __name__ == "__main__":
    main()
