# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Configuration for fine-tuning Gemma 3 VL 4B with MedPix dataset for image description
# torchrun --nproc-per-node=8 examples/vlm_finetune/finetune.py --config examples/vlm_finetune/internvl/internvl_3_5_4b.yaml

step_scheduler:
  global_batch_size: 16
  local_batch_size: 2
  ckpt_every_steps: 50
  val_every_steps: 50  # will run every x number of gradient steps
  num_epochs: 1

dist_env:
  backend: nccl
  timeout_minutes: 10

rng:
  _target_: nemo_automodel.components.training.rng.StatefulRNG
  seed: 42
  ranked: true

model:
  _target_: nemo_automodel.NeMoAutoModelForImageTextToText.from_pretrained
  pretrained_model_name_or_path: OpenGVLab/InternVL3_5-4B-hf

# peft:
#   _target_: nemo_automodel.components._peft.lora.PeftConfig
#   match_all_linear: False
#   exclude_modules:  # exclude all vision/audio modules and lm_head
#     - "*visual*"
#     - "*vision*"         # Vision encoder
#     - "*audio*"   # Audio encoder
#     - "*lm_head*"       # Output layer
#   dim: 16
#   alpha: 16
#   use_triton: False

checkpoint:
  enabled: true
  checkpoint_dir: checkpoints/
  model_save_format: safetensors

distributed:
  dp_size: none
  tp_size: 1
  cp_size: 1

distributed_config:
  _target_: nemo_automodel.components.distributed.config.FSDP2Config
  sequence_parallel: false

loss_fn:
  _target_: nemo_automodel.components.loss.masked_ce.MaskedCrossEntropy

dataset:
  _target_: nemo_automodel.components.datasets.vlm.datasets.make_medpix_dataset
  path_or_dataset: mmoukouba/MedPix-VQA
  split: train[:1000]


dataloader:
  _target_: torchdata.stateful_dataloader.StatefulDataLoader
  num_workers: 0
  collate_fn:
    _target_: nemo_automodel.components.datasets.vlm.collate_fns.default_collate_fn

validation_dataset:
  _target_: nemo_automodel.components.datasets.vlm.datasets.make_medpix_dataset
  path_or_dataset: mmoukouba/MedPix-VQA
  split: validation[:100]
  
validation_dataloader:
  _target_: torchdata.stateful_dataloader.StatefulDataLoader
  num_workers: 0
  collate_fn:
    _target_: nemo_automodel.components.datasets.vlm.collate_fns.default_collate_fn

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-5
  weight_decay: 0.01
  betas: [0.9, 0.95]

freeze_config:
  freeze_embeddings: true
  freeze_vision_tower: true
  freeze_audio_tower: true
  freeze_language_model: false
  
# Uncomment and configure for W&B logging
# wandb:
#   project: 
#   entity: 
#   name: 
