# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Benchmark configuration for Qwen2.5-7B with LoRA
#
# To run this recipe, please use the following command:
# torchrun --nproc-per-node=1 nemo_automodel/recipes/llm/benchmark.py --config examples/llm_finetune/qwen/qwen2_5_7b_peft_benchmark.yaml

seed: 1111

# Benchmark section
benchmark:
  warmup_steps: 5
  peak_tflops: 989  # H100: 989, A100: 312
  nsys_start: -1    # Set to step number to profile (e.g., 10)
  nsys_end: -1      # Set to end step (e.g., 15)
  nsys_ranks: []    # e.g., [0] to profile rank 0
  num_nodes: 1

step_scheduler:
  global_batch_size: 32
  local_batch_size: 2
  ckpt_every_steps: 50
  val_every_steps: 1000
  max_steps: 10

dist_env:
  backend: nccl
  timeout_minutes: 1

rng:
  _target_: nemo_automodel.components.training.rng.StatefulRNG
  seed: 1111
  ranked: true

model:
  _target_: nemo_automodel.NeMoAutoModelForCausalLM.from_pretrained
  pretrained_model_name_or_path: Qwen/Qwen2.5-7B
  torch_dtype: bf16

peft:
  _target_: nemo_automodel.components._peft.lora.PeftConfig
  match_all_linear: true
  dim: 16
  alpha: 32
  dropout: 0.0
  use_triton: true

distributed:
  _target_: nemo_automodel.components.distributed.fsdp2.FSDP2Manager
  dp_size: none
  dp_replicate_size: 1
  tp_size: 1
  cp_size: 1
  sequence_parallel: false

loss_fn:
  _target_: nemo_automodel.components.loss.masked_ce.MaskedCrossEntropy

# Use MockIterableDataset for benchmarking (faster, no I/O)
dataset:
  _target_: nemo_automodel.components.datasets.llm.mock_iterable_dataset.MockIterableDataset
  vocab_size: 100
  seq_len: 4096
  num_samples: 1000000
  batch_size: 2

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: null  # Dataset already yields batches
  # Note: model_config will be auto-injected by train_ft.py for PP models

optimizer:
  _target_: torch.optim.AdamW
  betas: [0.9, 0.999]
  eps: 1e-8
  lr: 1.0e-5
  weight_decay: 0.01

# Uncomment and configure for W&B logging
# wandb:
#   project: <your_wandb_project>
#   entity: <your_wandb_entity>
#   name: qwen2_5_7b_peft_benchmark
#   save_dir: <your_wandb_save_dir> 