# Custom Qwen2.5-72B with combined projections for benchmarking
# Based on Qwen2_72B_peft_benchmark.yaml but using custom model implementation
# Similar to custom_llama3_3_70b_instruct_peft_benchmark.yaml

# To run this recipe:
#   automodel examples/llm_finetune/qwen/qwen2_5_32b_peft_benchmark.yaml --nproc-per-node 8
# Adjust --nproc-per-node to the number of GPUs available on your machine.

recipe:
  _target_: nemo_automodel.recipes.llm.train_ft.TrainFinetuneRecipeForNextTokenPrediction

seed: 42

# Benchmark section
benchmark:
  warmup_steps: 5
  peak_tflops: 989  # H100: 989, A100: 312
  nsys_start: -1    # Set to step number to profile (e.g., 10)
  nsys_end: -1      # Set to end step (e.g., 15)
  nsys_ranks: []    # e.g., [0] to profile rank 0
  num_nodes: 1

step_scheduler:
  global_batch_size: 32
  local_batch_size: 8
  ckpt_every_steps: 50
  val_every_steps: 1000
  max_steps: 10

dist_env:
  backend: nccl
  timeout_minutes: 1

rng:
  _target_: nemo_automodel.components.training.rng.StatefulRNG
  seed: 1111
  ranked: true

model:
  _target_: nemo_automodel.NeMoAutoModelForCausalLM.from_pretrained
  pretrained_model_name_or_path: Qwen/Qwen2.5-32B-Instruct
  torch_dtype: bf16
  force_hf: true

peft:
  _target_: nemo_automodel.components._peft.lora.PeftConfig
  match_all_linear: True
  dim: 16
  alpha: 32
  use_triton: True

checkpoint:
  enabled: false
  checkpoint_dir: checkpoints/
  model_save_format: safetensors
  save_consolidated: false

distributed:
  strategy: fsdp2
  dp_size: none
  tp_size: 1
  cp_size: 1
  pp_size: 4

  sequence_parallel: false
  activation_checkpointing: true

  pipeline:
    pp_schedule: interleaved1f1b
    pp_microbatch_size: 1
    layers_per_stage: 2
    scale_grads_in_schedule: false
    round_virtual_stages_to_pp_multiple: up
    dtype: bf16

loss_fn:
  _target_: nemo_automodel.components.loss.masked_ce.MaskedCrossEntropy

# Use MockIterableDataset for benchmarking (faster, no I/O)
dataset:
  _target_: nemo_automodel.components.datasets.llm.mock_iterable_dataset.MockIterableDataset
  vocab_size: 100
  seq_len: 4096
  num_samples: 1000000

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: null  # Dataset already yields batches
  # Note: model_config will be auto-injected by train_ft.py for PP models

optimizer:
  _target_: torch.optim.Adam
  betas: [0.9, 0.999]
  eps: 1e-8
  lr: 1.0e-5
  weight_decay: 0

lr_scheduler:
  lr_decay_style: cosine
  min_lr: 1.0e-6