name: Dependency CI

on:
  workflow_run:
    workflows: [Child Dependency]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo Output
        shell: bash
        run: echo "Installation Test and Validate PR title ran."
