name: Child Dependency

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo Output
        shell: bash
        run: echo "This job runs first"
